import { Post, User,Comment } from "./types";

const users: User[] = [
    {
      firstName: "Alice",
      lastName: "Smith",
      email: "alice.smith@example.com",
      avatars: "https://example.com/avatars/alice.png",
    },
    {
      firstName: "Bob",
      lastName: "Johnson",
      email: "bob.johnson@example.com",
      avatars: "https://example.com/avatars/bob.png",
    },
    {
      firstName: "Charlie",
      lastName: "Davis",
      email: "charlie.davis@example.com",
      avatars: "https://example.com/avatars/charlie.png",
    },
    {
      firstName: "Diana",
      lastName: "Martinez",
      email: "diana.martinez@example.com",
      avatars: "https://example.com/avatars/diana.png",
    },
    {
      firstName: "Ethan",
      lastName: "Clark",
      email: "ethan.clark@example.com",
      avatars: "https://example.com/avatars/ethan.png",
    },
    {
      firstName: "Fiona",
      lastName: "Miller",
      email: "fiona.miller@example.com",
      avatars: "https://example.com/avatars/fiona.png",
    },
    {
      firstName: "George",
      lastName: "Wilson",
      email: "george.wilson@example.com",
      avatars: "https://example.com/avatars/george.png",
    },
    {
      firstName: "Hannah",
      lastName: "Taylor",
      email: "hannah.taylor@example.com",
      avatars: "https://example.com/avatars/hannah.png",
    },
    {
      firstName: "Ian",
      lastName: "Anderson",
      email: "ian.anderson@example.com",
      avatars: "https://example.com/avatars/ian.png",
    },
    {
      firstName: "Jessica",
      lastName: "White",
      email: "jessica.white@example.com",
      avatars: "https://example.com/avatars/jessica.png",
    },
    {
      firstName: "Kyle",
      lastName: "Moore",
      email: "kyle.moore@example.com",
      avatars: "https://example.com/avatars/kyle.png",
    },
    {
      firstName: "Laura",
      lastName: "Scott",
      email: "laura.scott@example.com",
      avatars: "https://example.com/avatars/laura.png",
    },
    {
      firstName: "Michael",
      lastName: "Brown",
      email: "michael.brown@example.com",
      avatars: "https://example.com/avatars/michael.png",
    },
    {
      firstName: "Nina",
      lastName: "King",
      email: "nina.king@example.com",
      avatars: "https://example.com/avatars/nina.png",
    },
    {
      firstName: "Oliver",
      lastName: "Harris",
      email: "oliver.harris@example.com",
      avatars: "https://example.com/avatars/oliver.png",
    },
    {
      firstName: "Paula",
      lastName: "Wright",
      email: "paula.wright@example.com",
      avatars: "https://example.com/avatars/paula.png",
    },
    {
      firstName: "Quinn",
      lastName: "Mitchell",
      email: "quinn.mitchell@example.com",
      avatars: "https://example.com/avatars/quinn.png",
    },
    {
      firstName: "Ryan",
      lastName: "Perez",
      email: "ryan.perez@example.com",
      avatars: "https://example.com/avatars/ryan.png",
    },
    {
      firstName: "Sophia",
      lastName: "Campbell",
      email: "sophia.campbell@example.com",
      avatars: "https://example.com/avatars/sophia.png",
    },
    {
      firstName: "Thomas",
      lastName: "Evans",
      email: "thomas.evans@example.com",
      avatars: "https://example.com/avatars/thomas.png",
    },
    {
      firstName: "Uma",
      lastName: "Baker",
      email: "uma.baker@example.com",
      avatars: "https://example.com/avatars/uma.png",
    },
    {
      firstName: "Victor",
      lastName: "Carter",
      email: "victor.carter@example.com",
      avatars: "https://example.com/avatars/victor.png",
    },
    {
      firstName: "Wendy",
      lastName: "Nelson",
      email: "wendy.nelson@example.com",
      avatars: "https://example.com/avatars/wendy.png",
    },
    {
      firstName: "Xander",
      lastName: "Reed",
      email: "xander.reed@example.com",
      avatars: "https://example.com/avatars/xander.png",
    },
    {
      firstName: "Yara",
      lastName: "Morgan",
      email: "yara.morgan@example.com",
      avatars: "https://example.com/avatars/yara.png",
    },
    {
      firstName: "Zack",
      lastName: "Bell",
      email: "zack.bell@example.com",
      avatars: "https://example.com/avatars/zack.png",
    },
  ];

  const comments: Comment[] = [
    {
      content: "Great post! Really helpful insights.",
      author: users[2],
      replies: [],
      likes: 15,
      dislikes: 1,
    },
    {
      content: "I think you're missing an important point here.",
      author: users[5],
      replies: [
        {
          content: "What would you suggest adding?",
          author: users[6],
          replies: [],
          likes: 5,
          dislikes: 0,
        },
      ],
      likes: 12,
      dislikes: 2,
    },
    {
      content: "I prefer using GraphQL over REST for flexibility.",
      author: users[9],
      replies: [],
      likes: 20,
      dislikes: 3,
    },
    {
      content: "This article really cleared things up for me!",
      author: users[8],
      replies: [
        {
          content: "Glad to hear that!",
          author: users[3],
          replies: [],
          likes: 8,
          dislikes: 0,
        },
      ],
      likes: 22,
      dislikes: 0,
    },
    {
      content: "You should also mention the importance of testing.",
      author: users[10],
      replies: [
        {
          content: "Good point! I'll update the post.",
          author: users[0],
          replies: [],
          likes: 11,
          dislikes: 1,
        },
      ],
      likes: 14,
      dislikes: 1,
    },
    {
      content: "Does anyone know how to solve this issue?",
      author: users[14],
      replies: [
        {
          content: "Try using a different npm package.",
          author: users[16],
          replies: [],
          likes: 9,
          dislikes: 2,
        },
        {
          content: "Clearing the cache sometimes helps.",
          author: users[18],
          replies: [],
          likes: 6,
          dislikes: 1,
        },
      ],
      likes: 17,
      dislikes: 3,
    },
    {
      content: "Tailwind makes it so easy to customize!",
      author: users[22],
      replies: [
        {
          content: "I agree, especially with JIT mode.",
          author: users[23],
          replies: [],
          likes: 12,
          dislikes: 0,
        },
      ],
      likes: 21,
      dislikes: 0,
    },
    {
      content: "I think Bootstrap is still relevant for quick builds.",
      author: users[24],
      replies: [],
      likes: 19,
      dislikes: 2,
    },
    {
      content: "JWT tokens are great, but can be tricky to implement.",
      author: users[19],
      replies: [
        {
          content: "Agreed. Refresh tokens can be confusing.",
          author: users[20],
          replies: [],
          likes: 8,
          dislikes: 0,
        },
      ],
      likes: 25,
      dislikes: 4,
    },
    {
      content: "This is the most detailed guide I've seen!",
      author: users[12],
      replies: [],
      likes: 18,
      dislikes: 0,
    },
    {
      content: "Don't forget to handle edge cases properly.",
      author: users[17],
      replies: [
        {
          content: "Can you give an example of an edge case?",
          author: users[21],
          replies: [],
          likes: 7,
          dislikes: 1,
        },
      ],
      likes: 13,
      dislikes: 1,
    },
    {
      content: "This framework has made my life so much easier!",
      author: users[25],
      replies: [
        {
          content: "Same here! It has really sped up my development.",
          author: users[8],
          replies: [],
          likes: 14,
          dislikes: 0,
        },
      ],
      likes: 28,
      dislikes: 2,
    },
    {
      content: "What are your thoughts on using TypeScript everywhere?",
      author: users[13],
      replies: [
        {
          content: "I love it! Static typing prevents so many bugs.",
          author: users[11],
          replies: [],
          likes: 10,
          dislikes: 0,
        },
        {
          content: "It's great for teams but a bit overkill for small projects.",
          author: users[1],
          replies: [],
          likes: 9,
          dislikes: 3,
        },
      ],
      likes: 30,
      dislikes: 5,
    },
    {
      content: "Minifying files has boosted my site’s performance.",
      author: users[7],
      replies: [],
      likes: 20,
      dislikes: 1,
    },
    {
      content: "I need help with handling pagination in React.",
      author: users[15],
      replies: [
        {
          content: "Try using React Query.",
          author: users[4],
          replies: [],
          likes: 12,
          dislikes: 1,
        },
      ],
      likes: 24,
      dislikes: 3,
    },
  ];
  
  const posts: Post[] = [
    {
      content: "Here's my latest thoughts on web development...",
      author: users[0],
      replies: [comments[0], comments[1]],
      likes: 50,
      dislikes: 5,
    },
    {
      content: "Does anyone have experience with Docker and Prisma?",
      author: users[1],
      replies: [comments[2]],
      likes: 30,
      dislikes: 3,
    },
    {
      content: "React or Vue? What do you think?",
      author: users[2],
      replies: [
        {
          content: "I'm a fan of React!",
          author: users[3],
          replies: [],
          likes: 12,
          dislikes: 1,
        },
        {
          content: "I prefer Vue, but both are great.",
          author: users[4],
          replies: [],
          likes: 10,
          dislikes: 0,
        },
      ],
      likes: 25,
      dislikes: 4,
    },
    {
      content: "How do you manage state in large React apps?",
      author: users[5],
      replies: [comments[3]],
      likes: 40,
      dislikes: 2,
    },
    {
      content: "What’s the best way to deploy a Node.js app?",
      author: users[6],
      replies: [
        {
          content: "I recommend using Vercel for simplicity.",
          author: users[7],
          replies: [],
          likes: 18,
          dislikes: 1,
        },
      ],
      likes: 32,
      dislikes: 6,
    },
    {
      content: "Any tips on debugging JavaScript?",
      author: users[8],
      replies: [
        {
          content: "Console logging helps a lot!",
          author: users[9],
          replies: [],
          likes: 15,
          dislikes: 0,
        },
      ],
      likes: 22,
      dislikes: 1,
    },
    {
      content: "Should I use GraphQL or REST API?",
      author: users[10],
      replies: [
        {
          content: "GraphQL is great for complex queries.",
          author: users[11],
          replies: [],
          likes: 10,
          dislikes: 3,
        },
        {
          content: "REST is simpler for smaller projects.",
          author: users[12],
          replies: [],
          likes: 8,
          dislikes: 2,
        },
      ],
      likes: 35,
      dislikes: 8,
    },
    {
      content: "How do you optimize web performance?",
      author: users[13],
      replies: [
        {
          content: "Lazy loading images is effective.",
          author: users[14],
          replies: [],
          likes: 20,
          dislikes: 1,
        },
        {
          content: "Minifying CSS and JS files also helps.",
          author: users[15],
          replies: [],
          likes: 17,
          dislikes: 2,
        },
      ],
      likes: 44,
      dislikes: 3,
    },
    {
      content: "Any recommendations for learning TypeScript?",
      author: users[16],
      replies: [comments[1], comments[2]],
      likes: 38,
      dislikes: 4,
    },
    {
      content: "Is it worth switching to Next.js from CRA?",
      author: users[17],
      replies: [
        {
          content: "Yes, especially for SSR and routing.",
          author: users[18],
          replies: [],
          likes: 25,
          dislikes: 2,
        },
      ],
      likes: 40,
      dislikes: 3,
    },
    {
      content: "How do you handle authentication in web apps?",
      author: users[19],
      replies: [
        {
          content: "I use JWT tokens for most cases.",
          author: users[20],
          replies: [],
          likes: 18,
          dislikes: 2,
        },
        {
          content: "OAuth2 is also worth considering.",
          author: users[21],
          replies: [],
          likes: 15,
          dislikes: 1,
        },
      ],
      likes: 50,
      dislikes: 5,
    },
    {
      content: "Which CSS framework do you prefer: Tailwind or Bootstrap?",
      author: users[22],
      replies: [
        {
          content: "Tailwind gives you more control.",
          author: users[23],
          replies: [],
          likes: 12,
          dislikes: 0,
        },
        {
          content: "Bootstrap is better for quick prototyping.",
          author: users[24],
          replies: [],
          likes: 10,
          dislikes: 1,
        },
      ],
      likes: 33,
      dislikes: 7,
    },
    {
      content: "What’s the best way to learn full-stack development?",
      author: users[25],
      replies: [
        {
          content: "Start with HTML/CSS and move to JavaScript.",
          author: users[0],
          replies: [],
          likes: 18,
          dislikes: 0,
        },
        {
          content: "Learning the MERN stack is a good option.",
          author: users[1],
          replies: [],
          likes: 22,
          dislikes: 1,
        },
      ],
      likes: 60,
      dislikes: 4,
    },
  ];
export {posts,comments,users}